<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Astra.Sensor</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Zeek.fs" />
    <Compile Include="Suricata.fs" />
    <Compile Include="Agent.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Astra.Shared\Astra.Shared.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.SystemTextJson" Version="1.3.13" />
  </ItemGroup>
</Project>
